import re

with open("frontend/src/App.jsx", "r") as f:
    content = f.read()

replacements = {
    '"Qual è il rapporto tra le auto Tesla registrate e la disponibilità di stazioni di ricarica rapida?"': '"What is the ratio between registered Tesla cars and the availability of fast charging stations?"',
    '"Quali sono le 5 contee con più veicoli elettrici registrati?"': '"What are the top 5 counties with the most registered electric vehicles?"',
    '"Esiste una correlazione tra reddito medio della zona e adozione di EV?"': '"Is there a correlation between average area income and EV adoption?"',
    '"Quali reti di ricarica (ChargePoint, Tesla, ecc.) sono più diffuse in WA?"': '"Which charging networks (ChargePoint, Tesla, etc.) are most prevalent in WA?"',
    '"Qual è l\'autonomia media dei veicoli elettrici per marca?"': '"What is the average range of electric vehicles by brand?"',
    "Caricamento dati aggregati e calcoli Big Data in corso...": "Loading aggregate data and computing Big Data calculations...",
    "Impossibile caricare la dashboard:": "Unable to load dashboard:",
    "Verifica che il backend sia raggiungibile su": "Verify that the backend is reachable at",
    "Riprova": "Retry",
    "'Panoramica Base (SQL Only)'": "'Basic Overview (SQL Only)'",
    "'Marketing & Adozione (CSV + SQL)'": "'Marketing & Adoption (CSV + SQL)'",
    "'Infrastruttura & Ricarica (JSON + SQL)'": "'Infrastructure & Charging (JSON + SQL)'",
    "'Evoluzione Autonomia (SQL Only)'": "'Range Evolution (SQL Only)'",
    "Esplora gli insight incrociando SQL, JSON semi-strutturati e dati geografici di Kaggle.": "Explore insights by cross-referencing SQL, semi-structured JSON, and Kaggle geographical data.",
    "Aggiorna dati": "Update Data",
    "Aggiorna Dati": "Update Data",
    '"Veicoli elettrici (Volume)"': '"Electric Vehicles (Volume)"',
    '"Autonomia media (miglia)"': '"Average Range (miles)"',
    '"Stazioni di ricarica"': '"Charging Stations"',
    '"N/D (Richiede JSON)"': '"N/A (Requires JSON)"',
    '"Colonnine DC Fast"': '"DC Fast Chargers"',
    '"Top marche per numero di immatricolazioni (SQL)"': '"Top Brands by Registrations (SQL)"',
    '"Distribuzione autonomia (miglia) (SQL)"': '"Range Distribution (miles) (SQL)"',
    '"Top 10 contee per numero di EV (SQL)"': '"Top 10 Counties by EV Count (SQL)"',
    '"Trend Immatricolazioni EV per Anno (SQL)"': '"EV Registrations Trend by Year (SQL)"',
    '"Immatricolazioni"': '"Registrations"',
    '"Marketing & Adozione: Reddito vs Penetrazione EV Fascia Alta"': '"Marketing & Adoption: Income vs Premium EV Penetration"',
    '"Reddito medio"': '"Average income"',
    "'Reddito Medio ($)'": "'Average Income ($)'",
    '"Penetrazione Premium (%)"': '"Premium Penetration (%)"',
    "'Penetrazione Premium (%)'": "'Premium Penetration (%)'",
    '"Contea"': '"County"',
    "Identificazione Opportunità di Mercato": "Market Opportunity Identification",
    "Questa vista incrocia il": "This view cross-references the",
    "reddito medio delle contee (Kaggle CSV)": "average county income (Kaggle CSV)",
    "con la penetrazione percentuale di": "with the percentage penetration of",
    "Tesla, Lucid, e Rivian": "Tesla, Lucid, and Rivian",
    "sul totale dei veicoli elettrici immatricolati nella contea.": "on the total electric vehicles registered in the county.",
    "Reddito Medio": "Average Income",
    "EV Totali": "Total EVs",
    "EV Premium": "Premium EVs",
    "Penetrazione %": "Penetration %",
    '"Infrastruttura & Sotto-Servizio: EV per Colonnina Rapida (Deficit Ricarica)"': '"Infrastructure & Under-Service: EVs per Fast Charger (Charging Deficit)"',
    "'Rapporto EV / Colonnina DC Fast'": "'EV / DC Fast Charger Ratio'",
    "Aree Sotto-Servite Critiche (Peggior Deficit)": "Critical Under-Served Areas (Worst Deficit)",
    "Rapporto numerico tra i veicoli immatricolati nella contea e le colonnine rapide DC Fast (Level 3) censite nel dataset JSON. Le barre in rosso rappresentano i 3 mercati con il peggior deficit infrastrutturale.": "Numerical ratio between vehicles registered in the county and DC Fast (Level 3) chargers surveyed in the JSON dataset. Red bars represent the 3 markets with the worst infrastructure deficit.",
    "Contea di": "County of",
    "EV registrate vs solo": "EV registered vs only",
    "stazioni veloci.": "fast stations.",
    '"Quota per network di ricarica (JSON)"': '"Charging Network Share (JSON)"',
    '"Evoluzione Autonomia Media (Miglia) per Produttore negli Anni"': '"Average Range Evolution (Miles) by Manufacturer over Years"',
    "Evoluzione della Tecnologia delle Batterie": "Battery Technology Evolution",
    "Analisi dell'efficienza reale dei pacchi batteria dei veicoli filtrati per anno dal 2012 in poi. Questa vista permette di identificare i produttori con la migliore evoluzione tecnologica e costanza nel tempo.": "Analysis of the real efficiency of battery packs of vehicles filtered by year from 2012 onwards. This view allows identifying manufacturers with the best technological evolution and consistency over time.",
    "Nota:": "Note:",
    "I dati dell'autonomia considerano esclusivamente i veicoli con un'autonomia reale certificata maggiore di zero, escludendo le stime nulle per evitare distorsioni nel calcolo medio.": "Range data exclusively consider vehicles with a certified real range greater than zero, excluding null estimates to avoid distortions in the average calculation.",
    "Valutazione Sperimentale": "Experimental Evaluation",
    "Benchmark eseguiti a richiesta: il primo replica il dataset reale a 1x/5x/10x e confronta i tempi": "Benchmarks performed on demand: the first replicates the real dataset to 1x/5x/10x and compares the times",
    "di aggregazione Pandas vs PySpark; il secondo confronta le risposte della crew con query SQL note a priori.": "of aggregation Pandas vs PySpark; the second compares the crew's answers with a priori known SQL queries.",
    "Pandas vs PySpark al crescere del Volume": "Pandas vs PySpark as Volume grows",
    '"In corso..."': '"Running..."',
    '"Esegui"': '"Run"',
    "Premi \"Esegui\" per replicare il dataset (1x/5x/10x) e confrontare i tempi di aggregazione.": "Press \"Run\" to replicate the dataset (1x/5x/10x) and compare aggregation times.",
    "Può richiedere qualche decina di secondi (avvio di Spark incluso).": "It may take a few tens of seconds (Spark startup included).",
    "Accuratezza Text-to-SQL (Effectiveness)": "Text-to-SQL Accuracy (Effectiveness)",
    '"Corretto"': '"Correct"',
    '"Errato"': '"Incorrect"',
    "Premi \"Esegui\" per confrontare le risposte dell'agente con query SQL note a priori.": "Press \"Run\" to compare the agent's answers with a priori known SQL queries.",
    "Valutazione Query — Le 5 V del Big Data": "Query Evaluation — The 5 Vs of Big Data",
    '"Volume", "Velocità", "Varietà", "Veridicità", "Valore"': '"Volume", "Velocity", "Variety", "Veracity", "Value"',
    'evaluation["Veridicità"]': 'evaluation["Veracity"]',
    '"Alta"': '"High"',
    '"Media"': '"Medium"',
    '"Bassa"': '"Low"',
    "Punteggio medio sulle 5 dimensioni": "Average score across 5 dimensions",
    "Affidabilità stimata:": "Estimated reliability:",
    "Pianificazione": "Planning",
    "Estrazione dati": "Data extraction",
    "Analisi": "Analysis",
    "Validazione": "Validation",
    '"Copiato!"': '"Copied!"',
    '"Copia Report"': '"Copy Report"',
    "Rappresentazione Grafica": "Graphical Representation",
    "Scarica Dati (CSV)": "Download Data (CSV)",
    "Stampa Report (PDF)": "Print Report (PDF)",
    "Inizializzazione ambiente Big Data in corso...": "Initializing Big Data environment...",
    "L'Architetto sta progettando il piano di estrazione dati...": "The Architect is designing the data extraction plan...",
    "L'Ingegnere SQL sta interrogando il database PostgreSQL...": "The SQL Engineer is querying the PostgreSQL database...",
    "L'Analista Dati sta eseguendo calcoli distribuiti via PySpark...": "The Data Analyst is performing distributed computations via PySpark...",
    "Il Guardiano sta redigendo l'analisi strategica finale...": "The Guardian is drafting the final strategic analysis...",
    "il backend ha risposto con un errore": "the backend responded with an error",
    "Errore di rete durante la comunicazione con il Backend": "Network error communicating with the Backend",
    '"**Errore:** ${error.message}"': '"**Error:** ${error.message}"',
    "Cronologia Ricerche": "Search History",
    "Nessuna ricerca salvata.": "No saved searches.",
    "Chiudi Cronologia": "Close History",
    "Apri Cronologia": "Open History",
    "Fai una domanda ai tuoi agenti...": "Ask your agents a question...",
    '"Elaborazione..."': '"Processing..."',
    '"Analizza"': '"Analyze"',
    "Suggerimenti di analisi:": "Analysis suggestions:",
    "STATO COMPLETAMENTO:": "COMPLETION STATUS:",
    "Stampa (PDF)": "Print (PDF)",
    "Progetto Architetturale di Big Data": "Big Data Architectural Project",
    "Progettato e Sviluppato da:": "Designed and Developed by:",
    "Università Roma Tre": "Roma Tre University"
}

for k, v in replacements.items():
    content = content.replace(k, v)

with open("frontend/src/App.jsx", "w") as f:
    f.write(content)

print("Translation completed.")
